# Site settings
title: YUNUS EMRE AYHAN
motto: Info is volatile, Blogs are permanent!
email: ayhanyunusemre@gmail.com
description: > # This is a personal webpage
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yunusemreayhan.github.io" # the base hostname & protocol for your site
# twitter_username: geninus
linkedin_username: yunus-emre-ayhan
github_username:  yunusemreayhan
disqus_name: personalwebsite-1
# Build settings
markdown: kramdown
